server:
  port: 8090

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级

    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: *


# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      # 官网地址 https://api.openai.com/
      api-host: https://pro-share-api.zcyai.com/

      # 官网申请 https://platform.openai.com/account/api-keys
      api-key: sk-sk-b0A0eSKTNxgBqrHv7aAa0808EdB849C89499D928648bD416

# 微信公众号配置信息
# originalid：原始 ID
# appid：个人 AppID
# token：开通接口服务自定义设置
wx:
  config:
    originalid: gh_8aed07a01479
    appid: wxa175a0b560bd00a2
    token: MYXH

# 监控
management:
  endpoints:
    web:
      exposure:
        # 暴露所有端点，包括自定义端点
        include: "*"

  endpoint:
    metrics:
      enabled: true

    health:
      # 显示详细的健康检查信息
      show-details: always

  metrics:
    export:
      prometheus:
        # 启用 Prometheus
        enabled: true

  prometheus:
    # 启用 Prometheus 端点
    enabled: true

  jmx:
    # 启用 JMX 监控
    enabled: true

  system:
    cpu:
      # 启用 CPU 监控
      enabled: true

    memory:
      # 启用内存监控
      enabled: true

# 日志
logging:
  level:
    root: info

  config: classpath:logback-spring.xml
